# .streamlit/secrets.toml

[mongo]
host = "localhost"
port = 27017
username = "xxx"
password = "xxx"

PASSWORD = "kYQaeGNL0NyOVnAh"
uri = f"mongodb+srv://brianelerner:{PASSWORD}@cerebra.manrrcm.mongodb.net/?retryWrites=true&w=majority"